# Generated by Django 4.2.3 on 2023-07-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('nick', models.CharField(blank=True, max_length=32)),
                ('year_of_birth', models.DecimalField(decimal_places=0, max_digits=4)),
                ('height', models.DecimalField(decimal_places=0, max_digits=3)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('position', models.CharField(choices=[('L', 'Libero'), ('S', 'Rozgrywający'), ('OH', 'Przyjmujący'), ('OP', 'Atakujący'), ('MB', 'Środkowy')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('players', models.ManyToManyField(through='api.PlayerMembership', to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='playermembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
